### PR TITLE
Reply to all participants in a Twitter conversation

### PR DESCRIPTION
**Pull request by Lancey6**
This PR automatically replies to all mentioned users in a status rather than just the author of the status. This allows a user to reply to Twitter conversations without having to manually include mentioned users.

### CODE REVIEW

**Comment by kylewm** [comment]
Ah, good idea. What do you think about automatically adding in @-names *if and only if* no @-names are mentioned in the status? That way if you just want to reply to one or two people in a thread, you can list them explicitly.

**Comment by Lancey6** [comment]
Maybe only if there's no @-names at the start of a post, rather than in the entire body? Otherwise it sounds good.

**Comment by kylewm** [comment]
hmm, to avoid false positives where someone unrelated to the conversation is mentioned in the reply? Maybe in that case, we should say, auto-prepend the @-names unless one or more of them is already mentioned in the status.

**Comment by Lancey6** [comment]
That makes the most sense. I'll work on it later tonight

**Comment by Lancey6** [comment]
Ok, I made it so it checks to see if any of the participating users are already mentioned in the status.

**Comment by kylewm** [comment]
Looking forward to trying this out, Thanks! (and your way of excluding the current user is much better than the quick-and-dirty BLACKLIST thing I was doing, so thank you for fixing that too)

I don't now what was going on with the merge conflicts, but I fixed them on the command line.

**Comment by Lancey6** [comment]
Most likely related to my repo being out of date. I'll have to fast forward it before I do anything else

**Pull request merged**
